service: update-todos
frameworkVersion: '3'

custom:
  restApiId:
    dev: o3d98utzsi
    prod: gkx214a0s8
  restApiRootResourceId:
    dev: 91ruh7
    prod: pae90i

provider:
  name: aws
  region: us-east-2
  runtime: python3.9
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/todos-lambda-policy
  apiGateway:
    restApiId: ${self:custom.restApiId.${opt:stage}}
    restApiRootResourceId: ${self:custom.restApiRootResourceId.${opt:stage}}

functions:
  update_todos:
    handler: handler.update
    events:
      - http: PUT /


