service: delete-todos
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/todos-lambda-policy

functions:
  hello:
    handler: handler.delete_todos
    events:
      - httpApi:
          path: /
          method: delete
