service: get-todos
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-2
  runtime: python3.9
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/todos-lambda-policy
  apiGateway:
    restApiId: o3d98utzsi
    restApiRootResourceId: 91ruh7

functions:
  get_todos:
    handler: handler.get
    events:
      - http: GET /



