name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy-create-todos:
    name: Deploy Create Todos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: create-todos-changes
        with:
          filters: |
            src:
              - 'create-todos/**'
      - if: steps.create-todos-changes.outputs.src == 'true'
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./create-todos && serverless deploy --stage prod"
          entrypoint: /bin/sh
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  deploy-delete-todos:
    name: Deploy Delete Todos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: delete-todos-changes
        with:
          filters: |
            src:
              - 'delete-todos/**'
      - if: steps.delete-todos-changes.outputs.src == 'true'
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./delete-todos && serverless deploy --stage prod"
          entrypoint: /bin/sh
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  deploy-get-todos:
    name: Deploy Get Todos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: get-todos-changes
        with:
          filters: |
            src:
              - 'get-todos/**'
      - if: steps.get-todos-changes.outputs.src == 'true'
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./get-todos && serverless deploy --stage prod"
          entrypoint: /bin/sh
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  deploy-update-todos:
    name: Deploy Update Todos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: update-todos-changes
        with:
          filters: |
            src:
              - 'update-todos/**'
      - if: steps.update-todos-changes.outputs.src == 'true'
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./update-todos && serverless deploy --stage prod"
          entrypoint: /bin/sh
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
